/* DATA QUERY LANGUAGE - WHERE - OPERATORS
CREATE TABLE STRUCTURE */

CREATE TABLE STUDENT (
    ROLL_NO INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    MARKS INT
);

INSERT INTO STUDENT
(ROLL_NO,NAME,AGE,CITY,MARKS)
VALUES
(1,"AKASH",10,"DELHI",50),
(2,"BINOD",11,"MUMBAI",55),
(3,"CHAHAT",12,"DELHI",54),
(4,"DHAIRYA",13,"JAIPUR",52),
(5,"EVA",14,"LUCKNOW",57);

-- (a) AND
SELECT 
    *
FROM
    STUDENT
WHERE
    MARKS > 50 AND CITY = 'MUMBAI';

-- (b) OR
SELECT 
    *
FROM
    STUDENT
WHERE
    MARKS >= 52 OR CITY = 'DELHI';

-- (c) NOT
SELECT 
    *
FROM
    STUDENT
WHERE
    CITY NOT IN ('DELHI' , 'MUMBAI');

-- (d) IN
SELECT 
    *
FROM
    STUDENT
WHERE
    CITY IN ('DELHI' , 'MUMBAI');

-- (e) BETWEEN
SELECT 
    *
FROM
    STUDENT
WHERE
    MARKS BETWEEN 53 AND 60;