/* DATA QUERY LANGUAGE - SELECT - FROM, WHERE, GROUP BY, HAVING, ORDER BY & LIMIT
CREATE TABLE STRUCTURE */

CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEE1(
EMPLOYEE_ID INT NOT NULL, EMPLOYEE_NAME VARCHAR(50) NOT NULL,
AGE INT NOT NULL, GENDER VARCHAR (20) NOT NULL,
DEPARTMENT VARCHAR(20) NOT NULL, SALARY INT NOT NULL); 

INSERT INTO EMPLOYEE1
(EMPLOYEE_ID, EMPLOYEE_NAME, AGE, GENDER, DEPARTMENT,SALARY)
VALUES
(101,"ABHISHEK",24,"M","MARKETING",25000),
(102,"BARKHA",25,"F","HR",30000),
(103,"CHARU",23,"F","FINANCE",20000),
(104,"DEV",22,"M","HR",24000),
(105,"ELIZEH",24,"F","OPERATIONS",25000),
(106,"FATIMA",26,"F","OPERATIONS",24000),
(107,"GAURAV",27,"M","MARKETING",30000),
(108,"HRITU",30,"F","MARKETING",35000),
(109,"ISHAAN",29,"M","FINANCE",28000),
(110,"JATIN",28,"M","HR",26000),
(111,"KANIKA",27,"F","MARKETING",32000),
(112,"LOVELY",30,"F","FINANCE",28000),
(113,"MANI",23,"M","HR",25000),
(114,"NITIN",26,"M","FINANCE",32000),
(115,"OM",31,"M","OPERATIONS",24000),
(116,"PARTHVI",25,"F","OPERATIONS",24000);

-- (a) WHERE CLAUSE
SELECT 
    *
FROM
    EMPLOYEE1
WHERE
    AGE > 26;
    
SELECT 
    *
FROM
    EMPLOYEE1
WHERE
    DEPARTMENT = 'OPERATIONS';
    
SELECT 
    *
FROM
    EMPLOYEE1
WHERE
    SALARY >= 25000
        AND DEPARTMENT = 'FINANCE';

-- (b) GROUP BY CLAUSE
SELECT 
    COUNT(EMPLOYEE_ID), DEPARTMENT
FROM
    EMPLOYEE1
GROUP BY DEPARTMENT;

SELECT 
    COUNT(EMPLOYEE_NAME), SALARY
FROM
    EMPLOYEE1
GROUP BY EMPLOYEE_NAME , SALARY;

-- (c) HAVING CLAUSE
SELECT 
    COUNT(EMPLOYEE_ID), DEPARTMENT
FROM
    EMPLOYEE1
GROUP BY DEPARTMENT
HAVING COUNT(EMPLOYEE_ID) >= 105;

-- (d) ORDER BY CLAUSE
SELECT 
    *
FROM
    EMPLOYEE1
ORDER BY SALARY ASC;

SELECT 
    *
FROM
    EMPLOYEE1
ORDER BY SALARY DESC;

SELECT 
    *
FROM
    EMPLOYEE1
ORDER BY EMPLOYEE_NAME , SALARY;

-- (e) LIMIT CLAUSE
SELECT 
    *
FROM
    EMPLOYEE1
LIMIT 5;

SELECT 
    *
FROM
    EMPLOYEE1
WHERE
    SALARY >= 26000
ORDER BY SALARY ASC
LIMIT 3;